services:
  app:
    build:
      context: ../app
      dockerfile: ../infra/app.Dockerfile
    image: app
    container_name: app
    ports:
      - "8080:80"
    depends_on:
      - auth_service
      - user_service
    restart: always

  auth_service:
    build:
      context: ..
      dockerfile: infra/auth_service.Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ../core/auth_service:/app
    restart: always

  user_service:
    build:
      context: ..
      dockerfile: infra/user_service.Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ../core/user_service:/app
    restart: always

  data:
    build:
      context: ../data
      dockerfile: ../infra/data.Dockerfile
    image: data
    container_name: data
    volumes:
      - ../data:/data/db
    restart: always
